/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_imagestitching_service_JNIService */

#ifndef _Included_com_example_imagestitching_service_JNIService
#define _Included_com_example_imagestitching_service_JNIService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_imagestitching_service_JNIService
 * Method:    callStitcher
 * Signature: (Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_com_example_imagestitching_service_JNIService_callStitcher
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
